### ISSUE TITLE
`precog2mtz` should accept globs

### ISSUE THREAD

**Issue by dennisbrookner** [rs-station/rs-booster#26]
If I'm understanding correctly, this function is currently written such that you would call, say:

```
rs.precog2mtz image1.ii image2.ii
```
whereas it would be convenient to do instead
```
rs.precog2mtz *.ii
```
If that is in fact the current functionality and I'm misunderstanding the code, my bad! I'm not sure how globs get unpacked in this situation

**Comment by JBGreisman** [comment]
globs like that are always unpacked by your shell (not Python), so those should be identical. I just checked, and you can definitely call things like this:

```
rs.precog2mtz --spacegroup 1 --cell 90 90 90 90 90 90 *.ii
```

Just a note, the spacegroup and cell parameters are required -- those are needed to write a MTZ file.

**Comment by dennisbrookner** [comment]
Neat, thanks!
