### ISSUE TITLE
`compute_weights()` returns the same dtype as `sigdf` when called with `DataSeries`

### ISSUE THREAD

**Issue by DHekstra** [rs-station/rs-booster#33]
Currently, diffmaps.weights.compute_weights returns a weights column with dtype Stddev rather than MTZReal. Obviously a minor issue.

**Comment by JBGreisman** [comment]
I agree with the main sentiment here -- as we move towards exposing a Python API for `rsbooster`, these helper functions should have a more clearly defined API. This should include more explicitly handling different inputs and coercing them to the proper output (Here, it should be `WeightDtype`).

Just to clarify the details here, the function `compute_weights()` doesn't return a `Stddev` type -- the function is written expecting numpy-like arrays:
https://github.com/rs-station/rs-booster/blob/4677572ff663d0b046a55f6fd6a8c85c4188cb2d/rsbooster/diffmaps/weights.py#L1-L13
The `Stddev` output only occurs if it is called with DataSeries (i.e. `compute_weights(ds["F"], ds["SigF"])`). If it were called with true arrays, the output would just be a plain Numpy array (i.e. `compute_weights(ds["F"]).to_numpy(), ds["SigF"].to_numpy()`). I agree that when the return type is a `DataSeries`, that it should have the proper `WeightDtype`. 

Until this API is revised, here's an example usage from `rs.diffmap`: https://github.com/rs-station/rs-booster/blob/4677572ff663d0b046a55f6fd6a8c85c4188cb2d/rsbooster/diffmaps/diffmap.py#L98-L100

**Comment by DHekstra** [comment]
Yes, your snippet from diffmap.py is exactly what I am doing now. Much of the code is already close to functional for API purposes with some wrangling of inputs and outputs. We can discuss at some point how to get to full API functionality!
